# Generated by Django 5.2.6 on 2025-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0016_alter_topology_parser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topology",
            name="label",
            field=models.CharField(
                choices=[("zerotier", "ZeroTier"), ("ipsec", "IPSec")],
                default="zerotier",
                max_length=64,
                verbose_name="label",
            ),
        ),
    ]
