# Generated by Django 5.2.6 on 2025-09-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topology", "0017_alter_topology_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topology",
            name="label",
            field=models.CharField(
                choices=[("zerotier", "ZEROTIER"), ("ipsec", "IPSEC")],
                default="zerotier",
                max_length=64,
                verbose_name="label",
            ),
        ),
    ]
